# Generated by Django 4.0.4 on 2022-06-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sysemail',
            fields=[
                ('id_config', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, null=True)),
                ('passemail', models.CharField(max_length=100, null=True)),
                ('recivedemail', models.CharField(max_length=100, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
                ('contentemail', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
