# Generated by Django 4.0.4 on 2022-06-17 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id_param', models.AutoField(primary_key=True, serialize=False)),
                ('time_check', models.IntegerField(choices=[(10, '10min'), (20, '20min'), (30, '30min')])),
            ],
        ),
        migrations.DeleteModel(
            name='Parameters',
        ),
    ]
