# Generated by Django 4.0.4 on 2022-06-17 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_parameter_delete_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysemail',
            name='time_mail',
            field=models.IntegerField(choices=[(10, '10min'), (20, '20min'), (30, '30min')], default=0),
            preserve_default=False,
        ),
    ]
