# Generated by Django 4.0.4 on 2022-06-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_sysemail_time_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysemail',
            name='time_mail',
            field=models.IntegerField(choices=[(60, '1 hora'), (120, '2 horas'), (240, '3 horas')]),
        ),
    ]
