# Generated by Django 4.0.5 on 2022-06-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0005_alter_sysemail_time_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='time_check',
            field=models.IntegerField(choices=[(300, '5min'), (600, '10min'), (1200, '20min'), (1800, '30min')]),
        ),
    ]
