# Generated by Django 4.0.5 on 2022-07-01 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0006_alter_parameter_time_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='time_check',
            field=models.IntegerField(choices=[(60, '1 min'), (120, '2 min'), (300, '5 min'), (600, '10 min'), (1200, '20 min'), (1800, '30 min')]),
        ),
        migrations.AlterField(
            model_name='sysemail',
            name='time_mail',
            field=models.IntegerField(choices=[(1800, '30 min'), (3600, '1 hora'), (7200, '2 horas')]),
        ),
    ]
